reports:
  exclude_contracts:
    - Ownable
    - Context
    - ERC20
    - SafeERC20
    - MerkleProof
    - ReentrancyGuard
    - Address

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - rari-capital/solmate@6
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
      - '@rari=rari-capital/solmate@6'
networks:
  default: hardhat-fork
